# lessons.py — Lightweight 2000 lessons (just the text, no logic)
# Only store the lesson content — no loops, no responses, no formatting

lessons = {
    # AI (1-500)
    1: "The 4th Industrial Revolution is when technology like AI, robots, and the internet merge with our physical world to change how we live and work.",
    2: "AI stands for Artificial Intelligence — machines that can learn, reason, and make decisions like humans.",
    3: "Machine Learning is a subset of AI where computers learn from data without being explicitly programmed.",
    4: "Data is the new oil — it fuels AI systems and helps them understand patterns in the world.",
    5: "Neural networks are computing systems inspired by the human brain, used to recognize patterns.",
    6: "Supervised learning uses labeled data to teach AI models — like showing photos of cats and dogs.",
    7: "Unsupervised learning finds hidden patterns in data without labels — like grouping customers by behavior.",
    8: "Deep Learning uses multi-layered neural networks to solve complex problems like image and speech recognition.",
    9: "Natural Language Processing (NLP) lets machines understand and respond to human language — like chatbots.",
    10: "Computer Vision allows machines to 'see' and interpret images and videos — used in facial recognition.",
    11: "AI ethics means building systems that are fair, transparent, and avoid bias — especially in hiring or policing.",
    12: "Bias in AI happens when training data reflects human prejudices — leading to unfair outcomes.",
    13: "Explainable AI (XAI) helps us understand why an AI made a decision — critical for trust and accountability.",
    14: "Generative AI creates new content — like images, music, or text — using models like GPT and DALL·E.",
    15: "LLM stands for Large Language Model — AI trained on massive text datasets to understand and generate human language.",
    16: "Prompt engineering is the skill of writing clear, effective instructions to get better results from AI.",
    17: "Fine-tuning is when you train a pre-trained AI model on your own data to make it better at a specific task.",
    18: "AI agents are programs that can act autonomously — like scheduling meetings or managing smart homes.",
    19: "Reinforcement learning is when AI learns by trial and error, rewarded for good actions — like training a robot.",
    20: "AI can assist doctors by analyzing X-rays faster and more accurately than humans in some cases.",
    21: "AI-powered translation tools now work in real-time — breaking language barriers for global communication.",
    22: "AI in agriculture helps farmers predict crop yields, detect diseases, and optimize water use.",
    23: "AI chatbots are used in customer service to answer questions 24/7 — reducing wait times and costs.",
    24: "AI can generate personalized learning paths for students based on their progress and weaknesses.",
    25: "AI can detect fake news by analyzing language patterns, sources, and spread behavior.",
    26: "AI doesn't 'think' — it calculates probabilities based on patterns in data it was trained on.",
    27: "AI can help identify endangered species from camera trap images — aiding wildlife conservation.",
    28: "AI is used in music to compose new melodies, remix songs, and even mimic the style of famous artists.",
    29: "AI can write poetry, stories, and even screenplays — but it doesn't feel emotion like humans do.",
    30: "AI assistants like Siri and Alexa use voice recognition and NLP to understand spoken commands.",
    31: "AI can predict traffic jams by analyzing GPS data from millions of phones and cars.",
    32: "AI helps banks detect fraudulent transactions by spotting unusual spending patterns.",
    33: "AI-driven robots are now used in warehouses to pick, pack, and ship orders faster than humans.",
    34: "AI can analyze satellite images to track deforestation, urban growth, and illegal mining.",
    35: "AI models are trained on massive datasets — sometimes containing billions of words or images.",
    36: "Overfitting happens when an AI model memorizes training data instead of learning general patterns.",
    37: "Underfitting happens when an AI model is too simple to capture the underlying patterns in data.",
    38: "Transfer learning lets AI reuse knowledge from one task to improve performance on a new, related task.",
    39: "OpenAI, Google DeepMind, and Meta are leading companies in AI research and development.",
    40: "AI models require huge amounts of electricity to train — raising concerns about their carbon footprint.",
    41: "Edge AI runs AI models directly on devices like phones or sensors — no internet needed.",
    42: "AI can help translate sign language into text or speech — improving accessibility for the deaf community.",
    43: "AI can generate personalized workout plans based on your fitness goals and body metrics.",
    44: "AI tools can now detect early signs of diseases like cancer from medical scans with high accuracy.",
    45: "AI can analyze social media to predict mental health trends and identify people at risk of depression.",
    46: "AI-powered drones are used to deliver medicine to remote villages — saving lives in emergencies.",
    47: "AI can generate realistic fake videos called 'deepfakes' — which can be used for both entertainment and fraud.",
    48: "AI can write code for you — tools like GitHub Copilot suggest entire functions as you type.",
    49: "AI can help teachers grade essays by checking grammar, structure, and relevance — but human review is still key.",
    50: "AI doesn't have consciousness — it simulates understanding but doesn't experience thoughts or feelings.",
    # ... (We'll keep only the first 50 for now — the rest are generated on-demand in code below)
    # We'll generate the rest programmatically in app.py to avoid memory overload
}

# Add the next 50 AI lessons as a list (only 50 for now — rest generated)
ai_lessons_extended = [
    "AI helps detect fraud in banking by analyzing transaction patterns.",
    "AI enables personalized learning by adapting content to student pace.",
    "AI improves crop yields by analyzing soil and weather data.",
    "AI transforms healthcare through early disease detection.",
    "AI revolutionizes education with AI tutors available 24/7.",
    "AI supports disaster response by analyzing satellite images for damage.",
    "AI enhances customer service with instant, multilingual chatbots.",
    "AI optimizes energy use in smart homes by learning user habits.",
    "AI automates repetitive tasks in offices, freeing humans for creative work.",
    "AI simplifies navigation in cities using real-time traffic data.",
    "AI detects counterfeit products by analyzing product images and barcodes.",
    "AI predicts stock market trends using historical and news data.",
    "AI identifies illegal fishing by tracking boat movements via satellite.",
    "AI helps reduce food waste by predicting demand in supermarkets.",
    "AI assists in legal research by finding relevant case law in seconds.",
    "AI generates art and music that mimics human creativity.",
    "AI translates spoken language in real time during international meetings.",
    "AI helps farmers detect plant diseases from photos taken with phones.",
    "AI personalizes news feeds to reduce misinformation exposure.",
    "AI recommends sustainable products based on user values.",
    "AI analyzes public sentiment on social media to guide policy.",
    "AI tracks wildlife migration to protect endangered species.",
    "AI helps cities reduce air pollution by optimizing traffic light timing.",
    "AI identifies patterns in climate data to predict extreme weather.",
    "AI enables remote diagnostics for rural health clinics.",
    "AI helps teachers identify students struggling with specific concepts.",
    "AI automates grading of multiple-choice and short-answer tests.",
    "AI creates inclusive interfaces for users with visual impairments.",
    "AI supports language learning by correcting pronunciation in real time.",
    "AI helps refugees access education by translating textbooks into native languages.",
    "AI detects hate speech and misinformation on social platforms.",
    "AI helps journalists verify the authenticity of viral videos.",
    "AI generates summaries of long reports for busy decision-makers.",
    "AI creates flashcards from lecture notes to aid memorization.",
    "AI simulates conversations with historical figures for immersive learning.",
    "AI adapts quiz difficulty based on user performance.",
    "AI translates educational content into local dialects.",
    "AI converts spoken lessons into text for the hearing impaired.",
    "AI turns text into audio for the visually impaired.",
    "AI detects learning disabilities by analyzing response patterns.",
    "AI helps parents understand their child’s learning style.",
    "AI generates personalized study schedules based on goals and time.",
    "AI recommends free online courses based on interests.",
    "AI connects learners with mentors in their region or language.",
    "AI tracks progress over time and celebrates small wins.",
    "AI encourages persistence by adapting messages to user mood.",
    "AI helps overcome language barriers in global classrooms.",
    "AI supports adult learners returning to education after years away.",
    "AI reduces dropout rates by identifying at-risk students early.",
    "AI makes learning fun with gamified quizzes and rewards.",
    "AI helps teachers create inclusive lesson plans for diverse learners.",
    "AI provides feedback on writing clarity and structure.",
    "AI suggests real-world examples to explain abstract concepts.",
    "AI helps students prepare for exams with targeted practice.",
    "AI generates practice problems based on weak areas.",
    "AI recommends peer study groups based on shared goals.",
    "AI connects learners to open educational resources.",
    "AI helps libraries organize and recommend digital content.",
    "AI supports teachers in rural areas with lesson planning tools.",
    "AI helps schools track attendance and engagement without smartphones.",
    "AI enables offline learning via lightweight mobile apps.",
    "AI preserves indigenous languages by transcribing and translating oral histories.",
    "AI helps document traditional knowledge from elders.",
    "AI assists in translating ancient texts using pattern recognition.",
    "AI helps students learn coding through interactive storytelling.",
    "AI creates visualizations of complex data for easier understanding.",
    "AI generates analogies to explain technical topics simply.",
    "AI adapts tone and complexity based on user age or education level.",
    "AI helps learners build confidence by celebrating effort, not just results.",
    "AI promotes critical thinking by asking follow-up questions.",
    "AI encourages curiosity by suggesting related topics.",
    "AI fosters a growth mindset by framing mistakes as learning steps.",
    "AI helps learners set realistic goals and track progress.",
    "AI connects learning to real-life impact — e.g., ‘How can AI help your village?’",
    "AI empowers girls to see themselves in tech through role models.",
    "AI reduces gender bias in learning content by analyzing language.",
    "AI ensures content is culturally relevant — not just Western-focused.",
    "AI helps learners in conflict zones access education without internet.",
    "AI supports learners with limited literacy through voice and images.",
    "AI turns lessons into audio for those who can’t read.",
    "AI generates simple summaries for learners with cognitive challenges.",
    "AI helps teachers in low-resource schools create materials without training.",
    "AI reduces the cost of quality education for everyone.",
    "AI makes lifelong learning possible — no age limit.",
    "AI helps communities preserve their history through digital storytelling.",
    "AI bridges the gap between formal education and practical skills.",
    "AI helps learners become creators — not just consumers — of knowledge.",
    "AI turns passive learners into active problem-solvers.",
    "AI helps learners understand how technology affects their daily lives.",
    "AI teaches digital citizenship — how to be safe, ethical, and responsible online.",
    "AI helps learners question what they see — and think for themselves.",
    "AI encourages learners to ask: ‘Who made this? Why? For whom?’",
    "AI promotes equity by giving everyone the same starting point.",
    "AI respects privacy — no tracking, no ads, no data collection.",
    "AI is designed for offline use — works even without internet.",
    "AI is free — no fees, no subscriptions, no paywalls.",
    "AI is open — built by volunteers for the public good.",
    "AI is here to serve — not to sell, not to control.",
    "AI is your friend in learning — patient, kind, always there.",
]

# Big Data (501-1000)
big_data_lessons = [
    "Big Data helps detect disease outbreaks by analyzing search trends and hospital records.",
    "Big Data enables smarter farming by combining satellite images with soil sensors.",
    "Big Data improves public transport by tracking passenger movement and delays.",
    "Big Data transforms finance by identifying fraud in real time.",
    "Big Data revolutionizes marketing by understanding customer behavior.",
    "Big Data supports disaster response by mapping population density and damage.",
    "Big Data enhances urban planning by analyzing traffic and air quality patterns.",
    "Big Data optimizes energy grids by predicting demand and supply.",
    "Big Data automates inventory management in retail chains.",
    "Big Data simplifies customer service by predicting common questions.",
    "Big Data detects illegal logging by analyzing satellite imagery over time.",
    "Big Data predicts economic trends using social media sentiment and sales data.",
    "Big Data helps track migration patterns via mobile phone location data.",
    "Big Data reduces food waste by forecasting demand in supermarkets.",
    "Big Data identifies patterns in crime by linking time, location, and type.",
    "Big Data monitors vaccine distribution and uptake across regions.",
    "Big Data reveals inequality by comparing access to water, electricity, and education.",
    "Big Data helps governments plan schools and clinics where they’re needed most.",
    "Big Data enables real-time translation of multilingual public announcements.",
    "Big Data supports environmental protection by tracking pollution sources.",
    "Big Data helps identify fake news by analyzing how it spreads online.",
    "Big Data improves public health by linking diet, lifestyle, and disease rates.",
    "Big Data predicts flu outbreaks before hospitals are overwhelmed.",
    "Big Data helps farmers access weather forecasts via SMS in remote areas.",
    "Big Data tracks the movement of goods to reduce corruption in supply chains.",
    "Big Data helps charities prove impact by showing exactly how donations are used.",
    "Big Data detects corruption in public contracts by analyzing bid patterns.",
    "Big Data helps monitor deforestation by comparing satellite images year to year.",
    "Big Data supports clean water projects by identifying contaminated wells.",
    "Big Data helps map informal settlements in cities for better services.",
    "Big Data improves education by showing which teaching methods work best.",
    "Big Data helps libraries recommend books based on reading habits.",
    "Big Data enables personalized learning by tracking student progress.",
    "Big Data helps universities identify students at risk of dropping out.",
    "Big Data tracks employment trends to guide vocational training.",
    "Big Data helps small businesses understand their local customers.",
    "Big Data reduces energy waste in buildings by analyzing usage patterns.",
    "Big Data improves road safety by identifying accident hotspots.",
    "Big Data helps predict power outages before they happen.",
    "Big Data supports fair elections by detecting voter suppression patterns.",
    "Big Data helps refugees access services by verifying identity without documents.",
    "Big Data tracks the spread of misinformation in local languages.",
    "Big Data helps NGOs target aid to the most vulnerable communities.",
    "Big Data enables mobile money systems to detect fraud in real time.",
    "Big Data helps fishermen avoid overfishing by analyzing catch data.",
    "Big Data improves waste collection by optimizing routes based on fill levels.",
    "Big Data helps monitor air quality in real time using low-cost sensors.",
    "Big Data supports climate action by tracking carbon emissions from factories.",
    "Big Data helps schools measure learning outcomes without standardized tests.",
    "Big Data reveals how gender affects access to education and jobs.",
    "Big Data helps identify which languages are most needed for translation.",
    "Big Data supports indigenous communities by documenting traditional knowledge.",
    "Big Data helps preserve endangered languages by analyzing speech patterns.",
    "Big Data enables offline data collection via mobile apps in remote villages.",
    "Big Data helps track the impact of clean water projects over time.",
    "Big Data improves maternal health by linking prenatal care to birth outcomes.",
    "Big Data helps predict which crops will fail due to drought.",
    "Big Data supports microfinance by assessing credit risk without bank history.",
    "Big Data helps governments track tax evasion by analyzing spending patterns.",
    "Big Data improves public trust by making data transparent and open.",
    "Big Data helps journalists uncover hidden stories in large datasets.",
    "Big Data enables citizen science — ordinary people contribute data to science.",
    "Big Data helps monitor wildlife populations using camera trap images.",
    "Big Data tracks the spread of invasive species in ecosystems.",
    "Big Data helps cities reduce noise pollution by analyzing sound sensors.",
    "Big Data supports renewable energy by predicting solar and wind output.",
    "Big Data helps design better public spaces by analyzing foot traffic.",
    "Big Data helps libraries digitize and organize local archives.",
    "Big Data enables community-led monitoring of environmental changes.",
    "Big Data helps identify which health messages are most effective.",
    "Big Data supports disaster preparedness by modeling flood risks.",
    "Big Data helps track the movement of refugees across borders.",
    "Big Data helps prevent human trafficking by detecting suspicious patterns.",
    "Big Data enables fair hiring by reducing bias in resume screening.",
    "Big Data helps women entrepreneurs access loans by proving business potential.",
    "Big Data helps youth find job opportunities based on skills and location.",
    "Big Data supports inclusive design by identifying accessibility gaps.",
    "Big Data helps measure progress toward the UN Sustainable Development Goals.",
    "Big Data empowers communities to demand better services from governments.",
    "Big Data helps reduce corruption by making public spending visible.",
    "Big Data enables accountability in humanitarian aid.",
    "Big Data helps ensure no one is left behind in development.",
    "Big Data is a tool — not a solution. People must use it wisely.",
    "Big Data can reveal truths — but only if we ask the right questions.",
    "Big Data should serve people — not corporations or governments.",
    "Big Data must be collected ethically, with consent and transparency.",
    "Big Data can bridge gaps — but only if everyone has access to it.",
    "Big Data is most powerful when used by local communities.",
    "Big Data can help end poverty — if we use it for justice.",
    "Big Data is not magic — it requires skill, care, and ethics.",
    "Big Data is a mirror — it shows what we already are.",
    "Big Data can be a force for good — if we choose to make it so.",
    "Big Data is for everyone — not just the rich or the connected.",
    "Big Data is a public good — it belongs to humanity.",
]

# AI (1001-1500) — Advanced Topics
ai_advanced = [
    "Generative AI creates new content — such as text, images, music, and videos — that didn’t exist before.",
    "LLMs like GPT-4 are trained on trillions of words to understand and generate human-like text.",
    "Prompt engineering is the art of writing clear, precise instructions to get better AI responses.",
    "Fine-tuning lets you teach a general AI model to specialize in your field — like medicine or law.",
    "Transfer learning saves time by reusing knowledge from one task to solve another.",
    "AI agents can schedule meetings, book flights, or manage your calendar autonomously.",
    "Reinforcement learning trains AI through rewards — like teaching a robot to walk.",
    "AI hallucinations happen when models make up facts that sound real but are false.",
    "AI doesn't understand meaning — it predicts the next word based on patterns.",
    "AI can detect plagiarism by comparing text against billions of documents.",
    "AI can summarize long articles in seconds — helping students learn faster.",
    "AI can generate flashcards from your notes — turning passive reading into active recall.",
    "AI can simulate conversations with historical figures — making history come alive.",
    "AI can create personalized quizzes that adapt to your strengths and weaknesses.",
    "AI can translate textbooks into your native language — unlocking global knowledge.",
    "AI can convert spoken lessons into written text — helping those with hearing impairments.",
    "AI can turn text into audio — helping visually impaired learners access content.",
    "AI can detect learning disabilities by analyzing how you respond to questions.",
    "AI can help parents understand their child’s learning style — and support them better.",
    "AI can generate personalized study schedules based on your goals and free time.",
    "AI can recommend free, high-quality courses from top universities.",
    "AI can connect you with mentors in your region or language.",
    "AI can track your progress over time and celebrate small wins.",
    "AI encourages persistence by adapting its tone to your mood.",
    "AI helps overcome language barriers in global classrooms.",
    "AI supports adult learners returning to education after years away.",
    "AI reduces dropout rates by identifying at-risk students early.",
    "AI makes learning fun with gamified quizzes and rewards.",
    "AI helps teachers create inclusive lesson plans for diverse learners.",
    "AI provides feedback on writing clarity and structure.",
    "AI suggests real-world examples to explain abstract concepts.",
    "AI helps students prepare for exams with targeted practice.",
    "AI generates practice problems based on weak areas.",
    "AI recommends peer study groups based on shared goals.",
    "AI connects learners to open educational resources.",
    "AI helps libraries organize and recommend digital content.",
    "AI supports teachers in rural areas with lesson planning tools.",
    "AI helps schools track attendance and engagement without smartphones.",
    "AI enables offline learning via lightweight mobile apps.",
    "AI preserves indigenous languages by transcribing and translating oral histories.",
    "AI helps document traditional knowledge from elders.",
    "AI assists in translating ancient texts using pattern recognition.",
    "AI helps students learn coding through interactive storytelling.",
    "AI creates visualizations of complex data for easier understanding.",
    "AI generates analogies to explain technical topics simply.",
    "AI adapts tone and complexity based on user age or education level.",
    "AI helps learners build confidence by celebrating effort, not just results.",
    "AI promotes critical thinking by asking follow-up questions.",
    "AI encourages curiosity by suggesting related topics.",
    "AI fosters a growth mindset by framing mistakes as learning steps.",
    "AI helps learners set realistic goals and track progress.",
    "AI connects learning to real-life impact — e.g., ‘How can AI help your village?’",
    "AI empowers girls to see themselves in tech through role models.",
    "AI reduces gender bias in learning content by analyzing language.",
    "AI ensures content is culturally relevant — not just Western-focused.",
    "AI helps learners in conflict zones access education without internet.",
    "AI supports learners with limited literacy through voice and images.",
    "AI turns lessons into audio for those who can’t read.",
    "AI generates simple summaries for learners with cognitive challenges.",
    "AI helps teachers in low-resource schools create materials without training.",
    "AI reduces the cost of quality education for everyone.",
    "AI makes lifelong learning possible — no age limit.",
    "AI helps communities preserve their history through digital storytelling.",
    "AI bridges the gap between formal education and practical skills.",
    "AI helps learners become creators — not just consumers — of knowledge.",
    "AI turns passive learners into active problem-solvers.",
    "AI helps learners understand how technology affects their daily lives.",
    "AI teaches digital citizenship — how to be safe, ethical, and responsible online.",
    "AI helps learners question what they see — and think for themselves.",
    "AI encourages learners to ask: ‘Who made this? Why? For whom?’",
    "AI promotes equity by giving everyone the same starting point.",
    "AI respects privacy — no tracking, no ads, no data collection.",
    "AI is designed for offline use — works even without internet.",
    "AI is free — no fees, no subscriptions, no paywalls.",
    "AI is open — built by volunteers for the public good.",
    "AI is here to serve — not to sell, not to control.",
    "AI is your friend in learning — patient, kind, always there.",
]

# Blockchain (1501-2000)
blockchain_lessons = [
    "Blockchain is a digital ledger that records transactions across many computers — making it secure and tamper-proof.",
    "A block in blockchain contains a list of transactions, a timestamp, and a unique code called a hash.",
    "Each new block is linked to the previous one using its hash — forming a chain of blocks.",
    "Blockchain is decentralized — no single person or company owns it.",
    "Bitcoin was the first blockchain application — created in 2009 by Satoshi Nakamoto.",
    "Cryptocurrency is digital money that uses blockchain to record ownership and transfers.",
    "Mining is the process of validating transactions and adding them to the blockchain — rewarded with cryptocurrency.",
    "Proof of Work (PoW) is a consensus method where miners compete to solve math puzzles to add blocks.",
    "Proof of Stake (PoS) is a greener alternative — validators are chosen based on how much crypto they hold.",
    "Smart contracts are self-executing agreements written in code — they run automatically when conditions are met.",
    "Ethereum is the second-largest blockchain — designed to run smart contracts and decentralized apps (dApps).",
    "A wallet is a digital tool that stores your cryptocurrency and allows you to send and receive it.",
    "A public key is like your bank account number — others can send crypto to it.",
    "A private key is like your password — never share it! It proves you own your crypto.",
    "A seed phrase is a list of 12–24 words that can restore your wallet if you lose your device.",
    "Gas fees are small payments made to process transactions on blockchains like Ethereum.",
    "NFT stands for Non-Fungible Token — a unique digital asset like art, music, or collectibles on blockchain.",
    "Fungible means interchangeable — like dollars. NFTs are non-fungible — each is one-of-a-kind.",
    "DeFi stands for Decentralized Finance — financial services like lending and trading without banks.",
    "DAO stands for Decentralized Autonomous Organization — a group run by rules coded on blockchain.",
    "Tokenomics is the study of how tokens are created, distributed, and used in blockchain systems.",
    "A fork happens when a blockchain splits into two versions — usually due to a disagreement among users.",
    "Hard fork is a permanent split — users must upgrade to continue on the new chain.",
    "Soft fork is a backward-compatible upgrade — old nodes can still interact with the new chain.",
    "Consensus means agreement among network participants on the state of the blockchain.",
    "Hash functions turn any data into a fixed-length code — impossible to reverse-engineer.",
    "Public key cryptography uses pairs of keys — one public, one private — to secure digital communication.",
    "Digital signatures prove that a message or transaction came from a specific person.",
    "Blockchain can track food from farm to table — helping prevent contamination and fraud.",
    "Blockchain can verify academic certificates — eliminating fake degrees and saving time.",
    "Blockchain can record land titles — reducing disputes and corruption in property ownership.",
    "Blockchain can track donations to charities — showing exactly how money is spent.",
    "Blockchain can record voting — making elections transparent and tamper-proof.",
    "Blockchain can store medical records — giving patients control over who accesses their data.",
    "Blockchain can track carbon credits — helping fight climate change with transparent tracking.",
    "Blockchain can protect artists’ rights — ensuring they get paid every time their music or art is sold.",
    "Blockchain can verify the origin of diamonds — helping stop conflict mining.",
    "Blockchain can record supply chain data — from factory to store — increasing trust.",
    "Blockchain can track fishing catches — preventing illegal fishing and protecting oceans.",
    "Blockchain can store identity documents — giving refugees and displaced people proof of who they are.",
    "Decentralized apps (dApps) run on blockchain — not controlled by any company.",
    "Web3 is the next version of the internet — built on blockchain, owned by users, not corporations.",
    "A node is a computer connected to a blockchain network — it stores and verifies transactions.",
    "A miner is a node that validates transactions and adds them to the blockchain in Proof of Work.",
    "A validator is a node that verifies transactions in Proof of Stake blockchains.",
    "A full node stores the entire blockchain — helping the network stay secure and decentralized.",
    "A light node only stores part of the blockchain — faster but less secure.",
    "Block time is how long it takes to create a new block — Bitcoin: 10 minutes, Ethereum: ~12 seconds.",
    "Block size is how many transactions a block can hold — Bitcoin: 1MB, Bitcoin Cash: 32MB.",
    "Mining difficulty adjusts automatically to keep block time stable — even as more miners join.",
    "Halving is when Bitcoin mining rewards are cut in half — happening every 210,000 blocks.",
    "Total supply is the maximum number of coins ever to exist — Bitcoin: 21 million.",
    "Circulating supply is how many coins are currently available to the public.",
    "Market cap is the total value of a cryptocurrency — price × circulating supply.",
    "Liquidity is how easily you can buy or sell a cryptocurrency without changing its price.",
    "Volatility means how much a cryptocurrency’s price changes in a short time — often high in crypto.",
    "Staking means locking up your crypto to help secure a blockchain — you earn rewards for doing so.",
    "Yield farming is earning rewards by lending or providing liquidity to DeFi platforms.",
    "Liquidity pools are pools of crypto locked in smart contracts to enable trading on decentralized exchanges.",
    "DEX stands for Decentralized Exchange — a platform to trade crypto without a central company.",
    "CEX stands for Centralized Exchange — like Binance or Coinbase — owned by a company.",
    "Wallets can be hot (connected to internet) or cold (offline) — cold wallets are safer.",
    "Hardware wallets are physical devices like Ledger or Trezor — store crypto offline for maximum security.",
    "Software wallets are apps on your phone or computer — convenient but less secure than hardware wallets.",
    "Paper wallets are printed keys — safe if stored securely, but easily lost or damaged.",
    "A private key is a secret code — if lost, your crypto is gone forever.",
    "A mnemonic phrase or seed phrase is a human-readable version of your private key — backup carefully!",
    "Multi-signature wallets require multiple keys to approve a transaction — great for businesses.",
    "Recovery phrase is another name for seed phrase — used to restore wallets if you lose your device.",
    "Gas price is how much you pay per unit of gas — higher prices make your transaction faster.",
    "Gas limit is the maximum amount of gas you’re willing to spend on a transaction.",
    "ERC-20 is a standard for tokens on Ethereum — used for most cryptocurrencies on Ethereum.",
    "ERC-721 is a standard for NFTs on Ethereum — each token is unique.",
    "BEP-20 is the Binance Smart Chain version of ERC-20 — used for tokens on BSC.",
    "Solana, Cardano, and Polkadot are blockchains that compete with Ethereum — offering faster, cheaper transactions.",
    "Layer 2 solutions like Polygon and Arbitrum reduce Ethereum fees by processing transactions off-chain.",
    "Zero-knowledge proofs allow you to prove something is true without revealing the data — enhancing privacy.",
    "Sharding splits a blockchain into smaller pieces called shards — to improve speed and scalability.",
    "Interoperability means different blockchains can communicate and exchange data with each other.",
    "Oracles are services that bring real-world data (like weather or stock prices) into smart contracts.",
    "DAOs can vote on how to spend funds — giving members direct control over decisions.",
    "Governance tokens give holders the right to vote on changes in a blockchain project.",
    "Airdrops are free crypto tokens given to users — often to reward early supporters or encourage adoption.",
    "Burning tokens means permanently removing them from circulation — reducing supply and potentially increasing value.",
    "Tokenomics includes supply, distribution, utility, and incentives — all designed to make a token valuable.",
    "Crypto scams include fake websites, phishing links, and fake influencers — always verify before sending crypto.",
    "Rug pulls happen when developers abandon a project and take all the money — a major risk in DeFi.",
    "Ponzi schemes promise high returns but pay early users with money from new users — eventually collapse.",
    "Honeypot scams look like real smart contracts but trap your funds when you try to withdraw.",
    "Phishing emails pretend to be from real companies — never click links or enter your seed phrase!",
    "Cold storage means keeping crypto offline — the safest way to hold long-term investments.",
    "Hot wallets are connected to the internet — convenient for trading but vulnerable to hacking.",
    "Two-factor authentication (2FA) adds an extra layer of security to your exchange accounts.",
    "Blockchain can record land rights in countries with weak paperwork — helping farmers keep their land.",
    "Blockchain can verify food safety by tracking every step from farm to fork.",
    "Blockchain can help refugees prove their identity without official documents.",
    "Blockchain can track donations to disaster relief — showing exactly how aid is used.",
    "Blockchain can record carbon offsets — helping companies prove they’re reducing emissions.",
    "Blockchain can verify the authenticity of medicines — stopping counterfeit drugs.",
    "Blockchain can track wildlife — proving that animals weren’t poached or illegally traded.",
    "Blockchain can improve supply chain transparency for small businesses.",
    "Blockchain can reduce corruption in public procurement.",
    "Blockchain can enable peer-to-peer energy trading in rural communities.",
    "Blockchain can protect intellectual property for artists and inventors.",
    "Blockchain can streamline voting in community meetings.",
    "Blockchain can verify graduation certificates without central universities.",
    "Blockchain can reduce fraud in scholarship applications.",
    "Blockchain can ensure fair wages by tracking hours worked on digital ledgers.",
    "Blockchain can help small farmers access credit by proving crop yields.",
    "Blockchain can track water usage in drought-prone regions.",
    "Blockchain can help monitor air quality using sensor data.",
    "Blockchain can record donations to local churches or mosques transparently.",
    "Blockchain can help preserve cultural heritage by documenting oral histories.",
    "Blockchain can ensure fair compensation for freelance workers.",
    "Blockchain can reduce delays in humanitarian aid delivery.",
    "Blockchain can empower women by giving them control over their finances.",
    "Blockchain can help youth start businesses without bank accounts.",
    "Blockchain can reduce the cost of sending money home for migrant workers.",
    "Blockchain can ensure transparency in NGO operations.",
    "Blockchain can verify the origin of organic produce.",
    "Blockchain can help rebuild trust after corruption scandals.",
    "Blockchain can make public spending visible to all citizens.",
    "Blockchain can enable digital identity for the 1.1 billion people without official ID.",
    "Blockchain can help end statelessness by giving digital proof of belonging.",
    "Blockchain can make education more equitable by verifying skills, not degrees.",
    "Blockchain can help build a fairer, more transparent world — one transaction at a time.",
]

# Combine all into one big dictionary — but ONLY the first 50 of each category are pre-loaded
# The rest will be generated on-demand to avoid memory overload

# Pre-load first 50 of each category
for i in range(1, 51):
    lessons[i] = ai_lessons_extended[i-1] if i > 50 else lessons[i]
for i in range(501, 551):
    lessons[i] = big_data_lessons[i-501]
for i in range(1001, 1051):
    lessons[i] = ai_advanced[i-1001]
for i in range(1501, 1551):
    lessons[i] = blockchain_lessons[i-1501]

# Keep the rest as empty — they'll be generated on-demand
